name: Security Audit
on: [push]
jobs:
  audit:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install slither-analyzer
      - run: slither ./contracts --exclude-dependencies
