name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install tensorflow-cpu==2.12.0  # Lightweight for CI
        
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=core --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  integration-tests:
    name: Integration Tests
    needs: unit-tests
    runs-on: ubuntu-latest
    services:
      ganache:
        image: trufflesuite/ganache:latest
        ports:
          - 8545:8545
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install blockchain deps
      run: |
        npm install -g ganache
        pip install brownie solana-py
        
    - name: Run integration tests
      env:
        ETH_RPC_URL: http://localhost:8545
      run: |
        pytest tests/integration/ -v
